version: "2"
run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - revive
    - unused

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
      - name: dot-imports
        disabled: true
      - name: unused-parameter
        disabled: true

issues:
  exclude-use-default: false
  exclude:
    - "exported: "
    - "package-comments: "
    - "dot-imports: "
    - "unused-parameter: "
