run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019" # ignore deprecations for now
    - linters:
        - errcheck
        - unused
      text: ".*"
