version: 2
project_name: gobookmarks
builds:
  - id: "gobookmarks"
    binary: gobookmarks
    dir: cmd/gobookmarks
    env:
      - CGO_ENABLED=1
    flags: ["-trimpath"]
    goos: ["{{ .Env.GOOS }}"]
    goarch: ["{{ .Env.GOARCH }}"]

archives:
  -
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - image_templates:
      - "arran4/gobookmarks:{{ .Tag }}"
      - "arran4/gobookmarks:latest"
    dockerfile: Dockerfile
    goos: linux
    goarch: "{{ .Env.GOARCH }}"
    use: buildx
  - image_templates:
      - "ghcr.io/arran4/gobookmarks:{{ .Tag }}"
      - "ghcr.io/arran4/gobookmarks:latest"
    dockerfile: Dockerfile
    goos: linux
    goarch: "{{ .Env.GOARCH }}"
    use: buildx
nfpms:
  -
    vendor: Ubels Software Development
    homepage: https://github.com/arran4/
    maintainer: Arran Ubels <arran@ubels.com.au>
    description: NA
    license: Private
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    release: 1
    section: default
    priority: extra
    scripts:
      postinstall: packaging/postinstall.sh
    contents:
      - src: packaging/systemd/gobookmarks.service
        dst: /lib/systemd/system/gobookmarks.service
        type: config
      - src: packaging/rc.d/gobookmarks
        dst: /usr/local/etc/rc.d/gobookmarks
        type: config
      - src: packaging/config.json
        dst: /etc/gobookmarks/config.json
        type: config
        file_info:
          mode: 0600
          owner: gobookmarks
          group: gobookmarks

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
