// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: queries-bookmarks.sql

package main

import (
	"context"
	"database/sql"
)

const createBookmarks = `-- name: CreateBookmarks :exec
INSERT INTO bookmarks (userReference, list)
VALUES (?, ?)
`

type CreateBookmarksParams struct {
	Userreference string
	List          sql.NullString
}

// This query adds a new entry to the "bookmarks" table and returns the last inserted ID as "returnthis".
func (q *Queries) CreateBookmarks(ctx context.Context, arg CreateBookmarksParams) error {
	_, err := q.db.ExecContext(ctx, createBookmarks, arg.Userreference, arg.List)
	return err
}

const getBookmarksForUser = `-- name: GetBookmarksForUser :one
SELECT Idbookmarks, list
FROM bookmarks
WHERE userReference = ?
`

type GetBookmarksForUserRow struct {
	Idbookmarks int32
	List        sql.NullString
}

// This query retrieves the "list" from the "bookmarks" table for a specific user based on their "users_idusers".
func (q *Queries) GetBookmarksForUser(ctx context.Context, userreference string) (*GetBookmarksForUserRow, error) {
	row := q.db.QueryRowContext(ctx, getBookmarksForUser, userreference)
	var i GetBookmarksForUserRow
	err := row.Scan(&i.Idbookmarks, &i.List)
	return &i, err
}

const updateBookmarks = `-- name: UpdateBookmarks :exec
UPDATE bookmarks
SET list = ?
WHERE userReference = ?
`

type UpdateBookmarksParams struct {
	List          sql.NullString
	Userreference string
}

// This query updates the "list" column in the "bookmarks" table for a specific user based on their "users_idusers".
func (q *Queries) UpdateBookmarks(ctx context.Context, arg UpdateBookmarksParams) error {
	_, err := q.db.ExecContext(ctx, updateBookmarks, arg.List, arg.Userreference)
	return err
}
