name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags: ['', 'exclude_gitlab', 'exclude_github']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build and Test
        run: |
          go vet -tags "${{ matrix.tags }}" ./...
          go build -tags "${{ matrix.tags }}" ./...
          go test -tags "${{ matrix.tags }}" ./...
